name: deploy to aws

on:
  workflow_dispatch:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - publish-event

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: 20.11.x
          cache: npm
          cache-dependency-path: "./src/package-lock.json"
      - name: SSG
        env:
          NUXT_CTF_SPACE_ID: ${{ secrets.NUXT_CTF_SPACE_ID }}
          NUXT_CTF_CDA_ACCESS_TOKEN: ${{ secrets.NUXT_CTF_CDA_ACCESS_TOKEN }}
          NUXT_CTF_MANAGEMENT_ACCESS_TOKEN: ${{ secrets.NUXT_CTF_MANAGEMENT_ACCESS_TOKEN }}
        run: |
          cd ./src
          npm ci
          npm run cf-generate-types
          npm run generate
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.DEPLOY_IAM_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Copy Files to S3
        run: |
          aws s3 sync --delete ./src/dist s3://${{ secrets.S3_BUCKET_NAME }}
